name: travel_booking
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^5.0.0
  retrofit: ^4.2.0
  get_it: ^7.2.0
  injectable: ^2.0.0
  json_annotation: ^4.7.0
  json_serializable: ^6.8.0
  cupertino_icons: ^1.0.6
  retrofit_generator: ^8.2.1
  flutter_screenutil: ^5.8.2
  flutter_easyloading: ^3.0.5
  intl:
  provider: ^6.1.2
  shared_preferences: 2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.0.0
  build_runner: ^2.3.0
  flutter_lints: ^3.0.0
  retrofit_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/images/
